apiVersion: v1
kind: ServiceAccount
metadata:
  name: zap-runner-ksa
  namespace: zap-runner
  annotations:
    iam.gke.io/gcp-service-account: zap-runner-runtime@pe3-devops-training-svaranasi.iam.gserviceaccount.com
