apiVersion: v1
kind: Service
metadata:
  name: student-registration-zap
  namespace: zap-runner
  labels:
    app: student-registration-zap
spec:
  type: LoadBalancer
  loadBalancerClass: networking.gke.io/l4-regional-external
  selector:
    app: student-registration-zap
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
