apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-app-ksa
  namespace: student-app
  annotations:
    iam.gke.io/gcp-service-account: pe3-svaranasi-app-runtime@pe3-devops-training-svaranasi.iam.gserviceaccount.com
